### ISSUE TITLE
Test for growth model

### ISSUE THREAD

**Issue by marklhc** [Gengrui-Zhang/R2spa#19]
See whether the syntax for `tspa` still works for `lavaan::growth()` models.

**Comment by marklhc** [comment]
Fix a typo of `L3` for both vignette and test file

**Comment by winniewytse** [comment]
Results from the joint model and 2SPA are a lot closer after fixing the typo. 

<img width="546" alt="Screenshot 2024-02-09 at 3 13 03 PM" src="https://github.com/Gengrui-Zhang/R2spa/assets/31665961/b7cbfa8b-fce0-4843-900d-93772f49afeb">

**Comment by marklhc** [comment]
Note that the mean of `i` does not need to be fixed to 0 in 2S-PA, as I modified in 73a479f
