### ISSUE TITLE
Document additional arguments for `tspa`

### ISSUE THREAD

**Issue by marklhc** [Gengrui-Zhang/R2spa#31]
```
Undocumented arguments in documentation object 'tspa'
     ‘vc’ ‘cross_loadings’
```

Could you help, @winniewytse?

**Comment by marklhc** [comment]
Also need to update the example after changing the output

```r
# multigroup, two-factor example
mod3 <- "
  # latent variables
    visual =~ x1 + x2 + x3
    speed =~ x7 + x8 + x9
"
fs_dat3 <- get_fs(HolzingerSwineford1939, model = mod3, std.lv = TRUE,
                  group = "school")
tspa(model = "visual ~ speed",
     data = fs_dat3,
     vc = attr(fs_dat3, "av_efs"),
     cross_loadings = attr(fs_dat3, "fsA"))
```

```
Error in `rownames<-`(`*tmp*`, value = fs) : 
     attempt to set 'rownames' on an object with no dimensions
   Calls: tspa -> tspaSingleGroupMF -> rownames<-
   Execution halted
```

**Comment by winniewytse** [comment]
Thanks Mark for checking functions and pointing out the issues. I've fixed the documentation. However, in the `covariance` branch, `tspa()` hasn't been adapted for multiple groups, as `get_fs()` was recently updated to provide the asymptotic variance-covariance matrices and loading matrices for multiple groups. I can add the extension to multiple groups to my to-do next.
