### ISSUE TITLE
Testing `get_fs()`

### ISSUE THREAD

**Issue by marklhc** [Gengrui-Zhang/R2spa#4]

**Comment by winniewytse** [comment]
Hello @marklhc, for running multigroup models, `lavaan` requires the grouping variable to be present in the data frame. Would you please add a column for the grouping variable to the output of `get_fs()`? Or please let us know if you suggest something otherwise. Thanks!

Winnie

**Comment by marklhc** [comment]
I don't think `get_fs()` currently supports multiple groups. I can try to implement it. Do you need that for your side or you can compute the factor scores from lavaan and add the grouping variables, like you did in the vignette?

**Comment by winniewytse** [comment]
Thank you for implementing the multigroup part for `get_fs()`! Yes, we do not need this new feature to build the `tspa()` function. I would like to put this note here as we thought about the connection between these two functions yesterday.

**Comment by marklhc** [comment]
@Gengrui-Zhang, there are some breaking changes I made in the latest update for `get_fs()` that cause some tests to fail. This includes that reliability is no longer returned. Could you take a look? Thank you and we can further discuss.

**Comment by Gengrui-Zhang** [comment]
Hi @marklhc , I have adapted the testing file for `get_fs()` by removing tests of reliability outputs and now the testing file should run without errors, and there should be no failed tests. 
I noticed that you had updated the tests for the `compute_fs` function. We can discuss more today regarding what tests we can add for the `get_fs()` function. Thanks so much!
Thanks!

**Comment by Gengrui-Zhang** [comment]
Hi @marklhc , I tried to edit the `test-get_fscore` file by adding the lower bound and upper bound of SE (i.e., 0 and 1), and also some similar tests for the Bartlett scores. Please let me know if I need to change/add anything. Thanks!
