### ISSUE TITLE
Add covariances between factors to 2spa models

### ISSUE THREAD

**Issue by winniewytse** [Gengrui-Zhang/R2spa#7]
@marklhc

**Comment by marklhc** [comment]
@marklhc  will export the se, loadings, and error covariances

**Comment by marklhc** [comment]
- [x] Create unit test to make sure the loading has the correct order
- [x] Update examples in vignette with the new syntax of `tspa()`

**Comment by winniewytse** [comment]
Hello @marklhc, 

I realized that the new way of performing 2S-PA that accounts for cross-loadings hadn't been implemented for multigroup examples. I believe we will need to tweak `get_fs()` to yield covariance matrices and loadings matrices for all groups, as well as `tspa()` to specify a model with multiple groups. 

I can take some time to work on this next if you wish to get this done before the end of the semester. 

Winnie

**Comment by marklhc** [comment]
Thanks @winniewytse. Do you think with `get_fs()`, we should output the data as a list instead of one data frame? I originally chose to output a combined data frame because it allows each row to have different standard errors. However, since lavaan does not do definition variables, and we rely on multiple group input for 2spa in this package, I'm thinking making the output a list may be more in line with the lavaan syntax and structure.

**Comment by winniewytse** [comment]
Thanks @marklhc. I think it's a good idea to output the data as a list. Just to clarify, do you prefer having a data frame per group and combining the data frames together into a list? If so, I think that works perfectly, and as you said, it's more in line with the lavvan syntax and structure. Would you define the asymptotic covariance matrices and loading matrices as attributes or elements of the list?

**Comment by winniewytse** [comment]
Hello @marklhc, I've fixed `tspa()` and the tests for it and now all tests pass. I quickly fixed them in case you would like to take time for a further look. Let me know if there's anything I need to change. Thanks!

**Comment by marklhc** [comment]
Thanks @Winnie. One thing i would point out you can use 
`expect_equal(ignore_attr = TRUE)` when comparing two objects but 
ignoring their attributes (e.g., names).
